apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-reader
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crb-config-reader-full-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: config-reader
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crb-config-reader-full-workshop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: config-reader
  namespace: workshop
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: sshfront
  name: sshfront
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sshfront
  template:
    metadata:
      labels:
        run: sshfront
    spec:
      containers:
      - image: lalyos/k8s-sshfront
        env:
        - name: NS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        name: sshfront
        command:
          - sshfront
          - -d
          - -e
          - -a=/ssh-auth.sh
          - -k=/tmp/id_rsa
          - /kube-exec.sh
        ports:
        - containerPort: 22
          protocol: TCP
      restartPolicy: Always
      serviceAccount: config-reader
      serviceAccountName: config-reader
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: sshfront
  name: sshfront
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    run: sshfront
  type: NodePort